version: '3.8'

services:
  endouic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: endouic_rtx3080
    shm_size: '8gb'
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['${GPU_ID:-0}']
              capabilities: [gpu]
    volumes:
      - ${DATASET_PATH:-/home/kkulawiec/Documents/low-light-image-enhancement/datasets/cec_dataset_only_dim}:/home/kkulawiec/Documents/low-light-image-enhancement/datasets/cec_dataset_only_dim:ro
      - ./experiments:/app/experiments
      - ./EndoUIC/options:/app/EndoUIC/options
      - /media/8TB_hdd/HOME/kkulawiec/low-light-image-enhancement/externals/EndoUIC/models/models:/app/experiments/train/models
      - ../LLCaps/utils:/app/llcaps_utils:ro
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONPATH=/app/EndoUIC:/app/llcaps_utils
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
    working_dir: /app/EndoUIC
    command: /bin/bash
